# Generated by Django 5.0 on 2023-12-20 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_gallarymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallarymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallarymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallarymodel',
            name='image',
            field=models.ImageField(upload_to='gallary/'),
        ),
    ]
