# Generated by Django 5.0 on 2023-12-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_gallarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallary/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallary',
                'verbose_name_plural': 'Gallries',
            },
        ),
    ]
