# Generated by Django 5.0 on 2023-12-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_categorymodel_menumodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_products', to='pages.categorymodel'),
        ),
    ]
