# Generated by Django 5.0 on 2023-12-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationModel',
        ),
    ]
